seriesList = [{'series': ['CT_YYYYMMDD_WO_1.2x0.6_Soft_Super_D_Thins_Chest'], 'patient': 'MRN00_YYYYMMDD'}, {'series': ['CT_YYYYMMDD_With_Soft_Super_D_Thins_60keV'], 'patient': 'MRN01_YYYYMMDD'}]
# Where patient studies and their series are stored
mainDirectory = "/path/to/mainDirectory"
# Where CSV files generated by 3D Slicer are saved
outputDirectory = "/path/to/outputDirectory"
